DROP TABLE IF EXISTS Motif CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Moderateur CASCADE;
DROP TABLE IF EXISTS Signale CASCADE;



CREATE TABLE Motif (
   MotifId INT PRIMARY KEY,
   Motif TEXT NOT NULL
);

CREATE TABLE Users (
   UserId INT PRIMARY KEY,
   MotifId INT,
   FOREIGN KEY (MotifId) REFERENCES Motif(MotifId)
);

CREATE TABLE Moderateur (
    ProfilId INT PRIMARY KEY,
    Description TEXT,
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(UserId)
);


CREATE TABLE Signale (

     User1 INT NOT NULL,
     User2 INT NOT NULL,
     Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     Motif INT NOT NULL,
     FOREIGN KEY (User1) REFERENCES Users(UserId),
     FOREIGN KEY (User2) REFERENCES Users(UserId),
     FOREIGN KEY (Motif) REFERENCES Motif(MotifId)

);
