version: '3.8'

services:
  service:
    build: .
    container_name: microservice_moderateur
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - melodyme-net

  postgres:
    image: postgres
    container_name: db_M_moderateur
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_moderateur
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - melodyme-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-service
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - melodyme-net



  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-service
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"     # pour les conteneurs
      - "29092:29092"   # pour localhost (hors Docker)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Kafka écoute sur deux ports différents (internes)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      # Kafka dit aux clients comment se connecter
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      # Indique à Kafka que PLAINTEXT et PLAINTEXT_HOST sont des protocols PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - melodyme-net

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8081:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: kafka:9092
    depends_on:
      - kafka
    networks:
      - melodyme-net

volumes:
  pgdata:

networks:
  melodyme-net:
