version: '3.8'



services:
  moderateur-service:
    build: .
    container_name: moderateur-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://moderateur-db:5432/moddb
      - SPRING_DATASOURCE_USERNAME=moderateur
      - SPRING_DATASOURCE_PASSWORD=modpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - moderateur-db
      -
  postgres:
    image: postgres
    container_name: db_moderateur
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_moderateur
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:







