apiVersion: v1
kind: Service
metadata:
  name: moderateur
spec:
  selector:
    app: moderateur
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderateur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderateur
  template:
    metadata:
      labels:
        app: moderateur
    spec:
      containers:
        - name: moderateur
          image: koundia/microservice_moderateur:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/db_moderateur"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
